name: "orionthewake's Action in Action"
description: "Greet someone and always return 42"
inputs:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  answer: # id of output
    description: "The answer to everything (always 42)"

runs:
  using: docker
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}